version: '3.4'

services:
  messengerapi:
    container_name: messengerapi
    build:
      context: .
      args:
        - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    ports:
      - "5201:8080"