version: '3.4'

services:
  authdatabase:
    container_name: container_name
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=database_name
    restart: always
    ports:
      - "5100:5432"
    volumes:
      - postgres_data_auth_database:/var/lib/postgresql/data/
